set(command "/Applications/CMake.app/Contents/bin/cmake;-P;/Users/bytedance/cpp/arrow/cpp/build-debug/gbenchmark_ep-prefix/src/gbenchmark_ep-stamp/download-gbenchmark_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/Applications/CMake.app/Contents/bin/cmake;-P;/Users/bytedance/cpp/arrow/cpp/build-debug/gbenchmark_ep-prefix/src/gbenchmark_ep-stamp/verify-gbenchmark_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/Applications/CMake.app/Contents/bin/cmake;-P;/Users/bytedance/cpp/arrow/cpp/build-debug/gbenchmark_ep-prefix/src/gbenchmark_ep-stamp/extract-gbenchmark_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
